In [69]:
import pandas as pd

In [71]:
df=pd.read_csv("carprices.csv")
df

                      Car  Mileage  Sell   Age
0                  BMW X5    69000  18000    6
1                  BMW X5    35000  34000    3
2                  BMW X5    57000  26100    5
3                  BMW X5    22500  40000    2
4                  BMW X5    46000  31500    4
5                 Audi A5    59000  29400    5
6                 Audi A5    52000  32000    5
7                 Audi A5    72000  19300    6
8                 Audi A5    91000  12000    8
9   Mercedez Benz C class    67000  22000    6
10  Mercedez Benz C class    83000  20000    7
11  Mercedez Benz C class    79000  21000    7
12  Mercedez Benz C class    59000  33000    5

In [73]:
dummies=pd.get_dummies(df.Car)
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [75]:
conc=pd.concat([df,dummies],axis='columns')

In [77]:
conc

,Car,Mileage,Sell,Age,Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [79]:
k=conc.drop(['Mercedez Benz C class','Car'],axis='columns')

In [81]:
k

    Mileage  Sell   Age  Audi A5  BMW X5
0     69000  18000    6    False    True
1     35000  34000    3    False    True
2     57000  26100    5    False    True
3     22500  40000    2    False    True
4     46000  31500    4    False    True
5     59000  29400    5     True   False
6     52000  32000    5     True   False
7     72000  19300    6     True   False
8     91000  12000    8     True   False
9     67000  22000    6    False   False
10    83000  20000    7    False   False
11    79000  21000    7    False   False
12    59000  33000    5    False   False

In [83]:
from sklearn.linear_model import LinearRegression

In [85]:
model=LinearRegression()

In [87]:
X=k.drop(['Mileage'],axis='columns')

In [89]:
X

    Sell   Age  Audi A5  BMW X5
0   18000    6    False    True
1   34000    3    False    True
2   26100    5    False    True
3   40000    2    False    True
4   31500    4    False    True
5   29400    5     True   False
6   32000    5     True   False
7   19300    6     True   False
8   12000    8     True   False
9   22000    6    False   False
10  20000    7    False   False
11  21000    7    False   False
12  33000    5    False   False

In [91]:
y=k.Mileage

In [93]:
y

0     69000
1     35000
2     57000
3     22500
4     46000
5     59000
6     52000
7     72000
8     91000
9     67000
10    83000
11    79000
12    59000
Name: Mileage, dtype: int64

In [95]:
model.fit(X,y)

LinearRegression()

In [97]:
model.predict([[18000,6,0,1]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([69321.62752477])

In [99]:
model.score(X,y)

0.9890455219242558